# Release template for publishing Zaion to a Homebrew tap.
# Before publishing, replace PLACEHOLDER_SHA256_* with values from the
# matching .sha256 assets generated by the release workflow.
class Zaion < Formula
  desc "Autonomous AI agent runtime with cryptographic provenance"
  homepage "https://github.com/zaimouren1/ZAION"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zaimouren1/ZAION/releases/download/v#{version}/zaion-v#{version}-x86_64-apple-darwin.tar.gz"
      sha256 "PLACEHOLDER_SHA256_INTEL"
    elsif Hardware::CPU.arm?
      url "https://github.com/zaimouren1/ZAION/releases/download/v#{version}/zaion-v#{version}-aarch64-apple-darwin.tar.gz"
      sha256 "PLACEHOLDER_SHA256_ARM"
    end
  end

  on_linux do
    url "https://github.com/zaimouren1/ZAION/releases/download/v#{version}/zaion-v#{version}-x86_64-unknown-linux-gnu.tar.gz"
    sha256 "PLACEHOLDER_SHA256_LINUX"
  end

  def install
    bin.install "zaion"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/zaion --version")
  end

  service do
    run [opt_bin/"zaion", "_daemon_run"]
    keep_alive true
    log_path var/"log/zaion/zaion.log"
    error_log_path var/"log/zaion/zaion-error.log"
    working_dir var/"lib/zaion"
  end
end
