//! CanonicalUsage — unified token accounting across all LLM provider API shapes.
//!
//! Hermes uses a `CanonicalUsage` dataclass with the same fields.
//! We capture every token category any provider might report.

use serde::{Deserialize, Serialize};

/// Unified token usage representation across all LLM APIs.
///
/// All fields default to 0 — providers only populate what they track.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct CanonicalUsage {
    /// Tokens sent as user / assistant context (prompt side).
    pub input_tokens: u64,
    /// Tokens generated by the model (completion side).
    pub output_tokens: u64,
    /// Tokens served from the provider's prompt cache (read hit).
    /// Billed at a lower rate (typically 10-20% of normal input price).
    pub cache_read_tokens: u64,
    /// Tokens written INTO the prompt cache.
    /// Usually billed at a small premium to create the cache entry.
    pub cache_write_tokens: u64,
    /// Tokens produced during extended-thinking / reasoning (o-series, claude thinking).
    /// Billed at output rate or a separate reasoning rate.
    pub reasoning_tokens: u64,
}

impl CanonicalUsage {
    /// Total tokens consumed (input + output + reasoning; excludes cache bookkeeping).
    pub fn total_tokens(&self) -> u64 {
        self.input_tokens + self.output_tokens + self.reasoning_tokens
    }

    /// True if any token field is non-zero.
    pub fn has_data(&self) -> bool {
        self.input_tokens > 0
            || self.output_tokens > 0
            || self.cache_read_tokens > 0
            || self.cache_write_tokens > 0
            || self.reasoning_tokens > 0
    }

    /// Accumulate another usage record into self (for session totals).
    pub fn accumulate(&mut self, other: &Self) {
        self.input_tokens += other.input_tokens;
        self.output_tokens += other.output_tokens;
        self.cache_read_tokens += other.cache_read_tokens;
        self.cache_write_tokens += other.cache_write_tokens;
        self.reasoning_tokens += other.reasoning_tokens;
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn default_is_zero() {
        let u = CanonicalUsage::default();
        assert_eq!(u.total_tokens(), 0);
        assert!(!u.has_data());
    }

    #[test]
    fn total_tokens_excludes_cache() {
        let u = CanonicalUsage {
            input_tokens: 100,
            output_tokens: 50,
            cache_read_tokens: 200,
            cache_write_tokens: 80,
            reasoning_tokens: 30,
        };
        assert_eq!(u.total_tokens(), 180);
        assert!(u.has_data());
    }

    #[test]
    fn accumulate_adds_fields() {
        let mut a = CanonicalUsage {
            input_tokens: 100,
            output_tokens: 50,
            ..Default::default()
        };
        let b = CanonicalUsage {
            input_tokens: 200,
            output_tokens: 80,
            cache_read_tokens: 40,
            ..Default::default()
        };
        a.accumulate(&b);
        assert_eq!(a.input_tokens, 300);
        assert_eq!(a.output_tokens, 130);
        assert_eq!(a.cache_read_tokens, 40);
    }
}
